apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-quotes-db
spec:
  selector:
    matchLabels:
      app: vehicle-quotes-db
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-quotes-db
    spec:
      containers:
        - name: vehicle-quotes-db
          image: k3d-test-app-registry:5050/postgres:v0.1
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: db-data-storage
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            # - name: POSTGRES_DB
            #   value: vehicle_quotes
            # - name: POSTGRES_USER
            #   value: vehicle_quotes
            # - name: POSTGRES_PASSWORD
            #   value: password
            
          # resources:
          #   limits:
          #     memory: 0.5Gi
          #     cpu: "2"
      volumes:
        - name: db-data-storage
          persistentVolumeClaim:
            claimName: db-data-persisent-volume-claim